set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i586)

set(CMAKE_C_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/i586-unknown-linux-musl-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/i586-unknown-linux-musl-g++)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/i586-unknown-linux-musl/sysroot)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
